apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-algorithm-egress
  namespace: ocean-compute
spec:
  podSelector:
    matchExpressions:
      - {key: component, operator: In, values: [algorithm]}
      - {key: allowNetworkAccess, operator: DoesNotExist}
    matchLabels:
      component: algorithm
  policyTypes:
  - Egress
  egress: []
