apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ocean-compute-operator
  name: ocean-compute-operator
  namespace: ocean-compute
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocean-compute-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocean-compute-operator
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: somekey
        - name: AWS_SECRET_ACCESS_KEY
          value: somesecret
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_BUCKET_OUTPUT
          value: outputbucket
        - name: AWS_BUCKET_ADMINLOGS
          value: adminbucket
        - name: IPFS_OUTPUT
          value: http://youripfsserver:5001
        - name: IPFS_OUTPUT_PREFIX
          value: http://youripfsserver:5001/ipfs/
        - name: IPFS_ADMINLOGS
          value: http://youradminipfsserver:5001
        - name: IPFS_ADMINLOGS_PREFIX
          value: http://youradminipfsserver:5001/ipfs/
        - name: IPFS_EXPIRY_TIME
          value: "3600"
        - name: IPFS_API_KEY
          value: "apikey"
        - name: IPFS_API_CLIENT
          value: "clientid"
        - name: STORAGE_CLASS
          value: standard
        - name: LOG_LEVEL
          value: DEBUG
        - name: POD_CONFIGURATION_CONTAINER
          value: oceanprotocol/pod-configuration:v1.0.1
        - name: NOTIFY_START_URL
          value: http://yourserver/
        - name: NOTIFY_STOP_URL
          value: http://yourserver/
        - name: POD_PUBLISH_CONTAINER
          value: oceanprotocol/pod-publishing:v1.0.0
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: postgres-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: postgres-config
        image: oceanprotocol/operator-engine:v1.0.1
        imagePullPolicy: Always
        name: ocean-compute-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: db-operator
      serviceAccountName: db-operator
      terminationGracePeriodSeconds: 30
